default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode
  username: <%= ENV['RAILS_DB_USERNAME'] %>
  password: <%= ENV['RAILS_DB_PASSWORD'] %>

development:
  <<: *default
  database: to_do_list_development

test:
  <<: *default
  database: to_do_list_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>